version: '2'
services:
  mycontactcard-app:
    image: mycontactcard
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=mycontactcard-couchbase
      - SPRING_COUCHBASE_BUCKET_NAME=MyContactCard
      - JHIPSTER_CACHE_REDIS_SERVER=redis://mycontactcard-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://mycontactcard-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  mycontactcard-couchbase:
    extends:
      file: couchbase.yml
      service: mycontactcard-couchbase
  mycontactcard-redis:
    extends:
      file: redis.yml
      service: mycontactcard-redis
